Repository movester/movester_client_backoffice, pull requests merged in 2022-01, with the labels that each got.

#9 [Feature/UI] Button/Input Component
  src/App.js
  src/components/utils/ButtonComponent.js
  src/components/utils/ContentComponent.js
  src/components/utils/ExampleComponent.js
  src/components/utils/HomeComponent.js
  src/components/utils/InputComponent.js
  src/components/utils/MainComponent.js
  src/components/utils/NavComponent.js
  src/components/utils/WhiteButtonComponent.js
  src/index.js
  src/theme.js
Labels: feature, UI/UX

#12 [Styled] react/function-component-definition
  .eslintrc.json
  src/App.js
  src/components/utils/Button.js
  src/components/utils/Content.js
  src/components/utils/Example.js
  src/components/utils/ExampleComponent.js
  src/components/utils/Home.js
  src/components/utils/Input.js
  src/components/utils/Main.js
  src/components/utils/Nav.js
  src/components/utils/WhiteButton.js
Labels: review me, styled

#28 #15 Feat: weekly stretching recommended UI
  src/App.js
  src/components/stretching/WeeklyStretchingList.js
  src/components/utils/Button.js
Labels: feature, UI/UX, review me

#30 #29 style: 디렉토리 구조 변경
  src/App.js
  src/components/Event/EventSearch.js
  src/components/EventComponent.js
  src/components/EventListComponent.js
  src/components/StretchingCreateComponent.js
  src/components/StretchingListComponent.js
  src/components/UserDetailComponent.js
  src/components/UserListComponent.js
  src/components/stretching/SearchStretching.js
  src/components/stretching/StetchingOptions.js
  src/components/user/UserCount.js
  src/components/user/Year.js
  src/components/userList/ListSearch.js
  src/components/userList/UserDetail.js
  src/components/utils/ListTable.js
  src/components/utils/ListTableNumbering.js
  src/components/utils/SelectBox.js
  src/dataList/listTableHeaders.js
  src/dataList/selectboxOptions.js
Labels: styled

#32 [Feat/UI] Nav 관리자 계정 추가
  src/components/stretching/WeeklyStretchingList.js
  src/components/utils/Nav.js
Labels: bug, feature, review me

#34 [Feat/UI] 일주일 스트레칭 검색 Modal 추가
  src/components/StretchingCreateComponent.js
  src/components/utils/Modal/SearchModal.js
Labels: feature, UI/UX

#36 #27 Feat: RegisterEvent, EventDetail UI etc
  src/App.js
  src/components/event/EventDetail.js
  src/components/event/RegisterEvent.js
  src/components/event/RegisterWinner.js
  src/components/event/Winner.js
  src/components/utils/ContentBox.js
  src/components/utils/Input.js
  src/components/utils/InputBox.js
  src/pages/event/RegisterEventPage.js
Labels: feature, UI/UX, review me
