Repository movester/movester_client_backoffice, pull requests merged in 2022-02, with the labels that each got.

#39 [Fix] 디렉토리 구조 변경
  src/App.js
  src/components/admin/AdminCreateComponent.js
  src/components/admin/AdminListComponent.js
  src/components/common/Content.js
  src/components/common/Example.js
  src/components/common/Home.js
  src/components/common/Main.js
  src/components/common/MenuItem.js
  src/components/common/Modal/DeleteModal.js
  src/components/common/Modal/ModalPortal.js
  src/components/common/Modal/SearchModal.js
  src/components/common/Nav.js
  src/components/common/SearchStretching.js
  src/components/common/Winner.js
  src/components/common/elements/Button.js
  src/components/common/elements/Center.js
  src/components/common/elements/ContentBox.js
  src/components/common/elements/Input.js
  src/components/common/elements/InputBox.js
  src/components/common/elements/InputTitle.js
  src/components/common/elements/ListTable.js
  src/components/common/elements/ListTableNumbering.js
  src/components/common/elements/OldInput.js
  src/components/common/elements/SelectBox.js
  src/components/common/elements/UserCount.js
  src/components/common/elements/WhiteButton.js
  src/components/common/elements/Year.js
  src/components/event/EventDetail.js
  src/components/event/EventListComponent.js
  src/components/event/RegisterEvent.js
  src/components/event/RegisterWinner.js
  src/components/login/LoginComponent.js
  src/components/stretching/RegisterStretching.js
  src/components/stretching/StretchingCreateComponent.js
  src/components/stretching/StretchingListComponent.js
  src/components/stretching/WeeklyStretchingList.js
  src/components/user/UserDetailComponent.js
  src/components/user/UserListComponent.js
  src/containers/LoginContainer.js
  src/modules/index.js
  src/modules/users.js
  src/store/admin/index.js
  src/store/configureStore.js
  src/store/event/index.js
  src/store/stretching/index.js
  src/store/user/index.js
Labels: fix

#44 feature: 43 - login feature implementation
  .eslintrc.json
  src/components/common/Home.js
  src/components/common/Nav.js
  src/components/login/LoginComponent.js
  src/hooks/useInputs.js
  src/index.js
  src/lib/api/auth.js
  src/lib/defaultClient.js
  src/store/admin/adminSlice.js
  src/store/admin/adminThunk.js
Labels: feature

#47 Feature/42-userList-pagenation
  .eslintrc.json
  src/App.js
  src/components/admin/AdminListComponent.js
  src/components/common/Nav.js
  src/components/common/Pagination.js
  src/components/common/elements/Button.js
  src/components/common/elements/Input.js
  src/components/common/elements/ListTable.js
  src/components/common/elements/SelectBox.js
  src/components/event/EventListComponent.js
  src/components/stretching/StretchingListComponent.js
  src/components/user/UserListComponent.js
  src/dataList/listTableHeaders.js
  src/dataList/selectboxOptions.js
  src/index.css
  src/lib/api/auth.js
Labels: feature

#48 feature: 46 - logout feature implementation
  src/components/common/Nav.js
  src/components/login/LoginComponent.js
  src/lib/api/auth.js
  src/store/admin/adminSlice.js
  src/store/admin/adminThunk.js
Labels: feature

#51 feature: 49 - register admin feature implementation
  .gitignore
  src/components/admin/AdminCreateComponent.js
  src/components/login/LoginComponent.js
  src/hooks/useInputs.js
  src/lib/api/auth.js
  src/lib/defaultClient.js
Labels: feature

#54 feature: 52 - admin password change feature implementation
  src/App.js
  src/components/admin/AdminCreateComponent.js
  src/components/admin/UpdatePassword.js
  src/components/common/Modal/UpdatePasswordModal.js
  src/components/common/Nav.js
  src/lib/api/auth.js
  src/store/admin/adminSlice.js
  src/store/admin/adminThunk.js
Labels: feature

#56 feature/45 user detail user api request
  .eslintrc.json
  src/components/common/elements/ListTable.js
  src/components/common/elements/UserTable.js
  src/components/common/elements/Year.js
  src/components/user/UserDetailComponent.js
  src/dataList/listTableHeaders.js
Labels: feature

#64 Feature/53 userlist search option
  .eslintrc.json
  src/components/admin/AdminListComponent.js
  src/components/common/Modal/SearchModal.js
  src/components/common/Pagination.js
  src/components/common/SearchStretching.js
  src/components/common/elements/ListTable.js
  src/components/common/elements/SelectBox.js
  src/components/common/elements/UserCount.js
  src/components/common/elements/UserTable.js
  src/components/common/elements/Year.js
  src/components/stretching/StretchingCreateComponent.js
  src/components/user/UserDetailComponent.js
  src/components/user/UserListComponent.js
  src/dataList/listTableHeaders.js
  src/dataList/selectboxOptions.js
Labels: feature, fix
